dist: trusty

services:
  - docker

# Temporarily update docker until travis supports compose v3.3+ files
before_install:
  - sudo service mysql stop
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose version

install:
  - cp -r config.template config
  - cp .env.template .env
  - wget https://raw.githubusercontent.com/FAForever/db/develop/test-data.sql

script:
  # Causes the docker-compose.yml to be syntax checked, without actually doing anything
  - docker-compose config
  # prepare services under test
  # faf-db first because it takes the longest to load
  - docker-compose up -d faf-db
  - docker-compose up -d faf-java-api faf-website
  # wait for db migrations to be run
  - sleep 60
  # insert test data
  - docker exec -i faf-db mysql -uroot -pbanana faf < test-data.sql
  # run test collection
  - docker run --network="host" -t postman/newman_ubuntu1404 run https://raw.githubusercontent.com/FAForever/faf-stack/${TRAVIS_BRANCH}/tests/postman-collection.json
